<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.1.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php if ($posts = $this->getRecent()): ?>
    <div class="widget-latest">
        <ul>
            <?php foreach ($posts as $post): ?>
                <li>
                <p class="latest-post"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a> <span class="date"><?php $_ct= new Zend_Date($post->getCreatedTime());
      echo $_ct->toString('MM/dd/yyy'); ?></span></p>
                <hr/>
                <p><?php echo $post->getShortContent(); ?></p>
              
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>