<?php
    $_field = $this->getField();
    $hlr = $this->helper("amscheckout");
    echo $hlr->getBeforeControlHtml($_field);
?>
<input placeholder="<?php echo $this->getStoreLabel('firstname') ?> <?php echo $_field['field_required'] ? "*" : "" ?>" type="text" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->getFieldName('firstname')?>" value="<?php echo $this->escapeHtml($this->getObject()->getFirstname()) ?>" title="<?php echo $this->getStoreLabel('firstname') ?>" maxlength="255" class="input-text <?php echo $_field['field_required'] ? "required-entry" : "" ?>" <?php echo $this->getFieldParams() ?> />
<?php echo $hlr->getAfterControlHtml($_field);?>
