<?php
    $_field = $this->getField();
    $hlr = $this->helper("amscheckout");
    echo $hlr->getBeforeControlHtml($_field);
?>
<input type="text" id="<?php echo $this->getFieldId('lastname')?>" name="<?php echo $this->getFieldName('lastname')?>" value="<?php echo $this->escapeHtml($this->getObject()->getLastname()) ?>" title="<?php echo $this->getStoreLabel('lastname') ?>" maxlength="255" placeholder="<?php echo $this->getStoreLabel('lastname') ?> <?php echo $_field['field_required'] ? "*" : "" ?>" class="input-text <?php echo $_field['field_required'] ? "required-entry" : "" ?>" <?php echo $this->getFieldParams() ?> />
<?php echo $hlr->getAfterControlHtml($_field);?>
