<?php

/**
 * Magictoolbox product list template for Magento store.
 * Allow use MagicTools on product list page.
 * @mail support@magictoolbox.com
 */

$_productCollection = $this->getLoadedProductCollection();

if($_productCollection && $_productCollection->count()) {
    $magicToolboxHelper = Mage::helper('magiczoomplus/settings');
    $tool = $magicToolboxHelper->loadTool('category');
    if(!$tool->params->checkValue('enable-effect', 'No')) {
        ob_start();
        require($magicToolboxHelper->getProductsListTemplateFilename());
        $contents = ob_get_contents();
        ob_end_clean();
        $group = 'category';
        require($magicToolboxHelper->getMagicToolboxListTemplateFilename());
        echo $contents;
    } else {
        require($magicToolboxHelper->getProductsListTemplateFilename());
    }
} else {
    // echo $this->__('There are no products matching the selection.');
}

?>
