<?php
/**
 * @category    Trmmarketing
 * @package     Trmmarketing_PopupWidgets
 * @copyright   Copyright (c) 2013 TRM Marketing LLC
 * @license     http://www.trm-marketing.com/solutions/license/TRM-Marketing-Standard-License-Agreement.html
 */  
			
			$popupModalColor = Mage::getStoreConfig('trmpopupconfig/trmpopupdesign_group/popupmodalcolor',Mage::app()->getStore());
			$popupModalOpacity = Mage::getStoreConfig('trmpopupconfig/trmpopupdesign_group/popupmodalopacity',Mage::app()->getStore());
			$popupModalInDuration = Mage::getStoreConfig('trmpopupconfig/trmpopupdesign_group/popupmodalinduration',Mage::app()->getStore());
			$popupModalOutDuration = Mage::getStoreConfig('trmpopupconfig/trmpopupdesign_group/popupmodaloutduration',Mage::app()->getStore());
			
			// excluse any of the specified user agents
			$arrParams = $this->getRequest()->getParams();
			
       
            $storeBaseUrl = Mage::GetBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);	
			$resource = Mage::getSingleton('core/resource');
			$read= $resource->getConnection('core_read');
			$popupTable = $resource->getTableName('popup');
			$store_id = $this->helper('core')->getStoreId();
			$select = $read->select()
			   ->from($popupTable,array('popup_id','title','template','filename','background_color','modal_background','modal_color','modal_video_mp4','modal_video_ogv','modal_opacity','modal_video_loop','cookie_value','cookie_expiry','width','height','popup_content','styles','delay','status','begin_time','end_time','sort_order'))
			   ->where('popup_id='.$arrParams['id'])
			   ->order('sort_order ASC') ;
			   
			$popups = $read->fetchAll($select);
			
			
			foreach ($popups as $item) :
			
			$helper = Mage::helper('cms');
			$processor = $helper->getBlockTemplateProcessor();
		
			
			?>
           
			<?php
			//modal appearance and overrides
			 
			if (!$popupModalColor == ""): 
			$modalColor = $popupModalColor; 
			else: 
			$modalColor = '#FFFFFF'; 
			endif;
			
			//modal color override
			if ($item['modal_color'] != "") $modalColor =  $item['modal_color'];
			
			//modal background image
			$modalBackground = "";
			if ($item['modal_background'] != ""):
			$modalBackground .= 'background-size:100% auto; background-image:url("'. Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .$item['modal_background'].'");'; 
			
			endif;
			
			$modalOpacity = "";
			if (!$popupModalOpacity == ""): 
			$modalOpacity = $popupModalOpacity; 
			else: 
			$modalOpacity =  '0.5'; 
			endif;
			if ($item['modal_opacity'] != "") $modalOpacity = $item['modal_opacity'];
			
			?>
			
            
			<style>
			
			
			#backgroundFade { background-color:<?php echo $modalColor; ?>; <?php echo $modalBackground; ?> height:140%; left:0px; margin:0px; padding:0px; position:absolute; top:0px; visibility:hidden; width:100%; z-index:160000; opacity:<?php echo $modalOpacity; ?>; }
			#closeLink { font-size:16px; color:#fff; position:absolute; right:10px; bottom:10px; }
			
			<?php echo $item['styles']; ?>
			
		</style>
        <script>
		var magentoPopupBox = Class.create({
		open : function () {
			//this._centerWindow(this.container);
			this._fade('open', this.container);
		},
		
		close : function () {
			this._fade('close', this.container);
		},
		
		_fade : function fadeBg(userAction,whichDiv){
			if(userAction=='close'){
				new Effect.Opacity('backgroundFade',
						   {duration:<?php if (!$popupModalOutDuration == ""): echo $popupModalOutDuration; else: echo '.5'; endif; ?>,
							from:<?php echo $modalOpacity; ?>,
							to:0,
							afterFinish:this._makeInvisible,
							afterUpdate:this._hideLayer(whichDiv)});
			}else{
				new Effect.Opacity('backgroundFade',
						   {duration:<?php if (!$popupModalInDuration == ""): echo $popupModalInDuration; else: echo '.5'; endif; ?>,
							from:0,
							to:<?php echo $modalOpacity; ?>,
							beforeUpdate:this._makeVisible,
							afterFinish:this._showLayer(whichDiv)});
			}
		},
		
		_makeVisible : function makeVisible(){
			$("backgroundFade").style.visibility="visible";
		},
	
		_makeInvisible : function makeInvisible(){
			$("backgroundFade").style.visibility="hidden";
		},
	
		_showLayer : function showLayer(userAction){
			$(userAction).style.display="block";
		},
		
		_hideLayer : function hideLayer(userAction){
			$(userAction).style.display="none";
		},
		
		_centerWindow : function centerWindow(element) {
			var windowHeight = parseFloat($(element).getHeight())/2; 
			var windowWidth = parseFloat($(element).getWidth())/2;
	
			if(typeof window.innerHeight != 'undefined') {
				$(element).style.top = Math.round(document.body.offsetTop + ((window.innerHeight - $(element).getHeight()))/2)+'px';
				$(element).style.left = Math.round(document.body.offsetLeft + ((window.innerWidth - $(element).getWidth()))/2)+'px';
			} else {
				$(element).style.top = Math.round(document.body.offsetTop + ((document.documentElement.offsetHeight - $(element).getHeight()))/2)+'px';
				$(element).style.left = Math.round(document.body.offsetLeft + ((document.documentElement.offsetWidth - $(element).getWidth()))/2)+'px';
			}
		},
		
		initialize : function(containerDiv) {
			this.container = containerDiv;
			if($('backgroundFade') == null) {
				var screen = new Element('div', {'id': 'backgroundFade'});
				document.body.appendChild(screen);
			}
			this._hideLayer(this.container);
		}
	});


		</script>
        <?php if($item['filename'] != "" || $item['background_color'] != ""):
		$backgroundSetup = 'background:';
		  
		if($item['filename'] != "") $backgroundSetup .= 'url(' . Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $item['filename'] .') no-repeat';
		if($item['background_color'] != "") $backgroundSetup .= ' '.$item['background_color'];
		$backgroundSetup .= ';';
		
		
		endif; ?>
        
          <?php 
		if (($item['width'] != '')&&($item['height'] != '')):
		$ml = round($item['width'] / 2);
        $mt = round($item['height'] / 2);
		endif;
		 ?>
         <style>
		#magentoPopupContainer  { position: fixed; <?php echo $backgroundSetup; ?> width: <?php echo $item['width']; ?>px; height: <?php echo $item['height']; ?>px; z-index: 160010; top:50%; left:50%; margin-left:-<?php echo $ml.'px'; ?>;  margin-top:-<?php echo $mt.'px'; ?>; /*visibility:hidden;*/ }
			
			<?php echo $item['styles']; ?>
		</style>
        
				<div id="magentoPopupContainer"><!-- TRM Marketing Promotional Pop-ups ver 2.7.9 -->
			    	<?php echo $processor->filter($item['popup_content']); ?>
					
                    <?php 
					if ($item['template'] != 'blank_no_close'): ?>
					<a id="closeLink" href="javascript:void(0);">Close [x]</a>
                    <?php endif; ?>
                    
                   
				</div>
            <script>
			Event.observe(window, 'load', function () { 
			//popup.phtml
			magentoPopup = new magentoPopupBox('magentoPopupContainer'); 
			openPopupDelay.delay(<?php echo $item['timestatus'] ?>);
			
			<?php
				if(($item['modal_video_mp4'] != "") || ($item['modal_video_ogv'] != "")):
				?>
				var video = new Videoplayer('<?php echo $item['modal_video_mp4']; ?>','<?php echo $item['modal_video_ogv']; ?>','<?php echo $item['modal_video_loop']; ?>');
				<?php
				endif;
				?>
			
			 });
			if(document.getElementById("closeLink")) {
			$('closeLink').observe('click', function(event) { magentoPopup.close();checkForVideo();
			 });
			}
			
			if(document.getElementById("closeLinkCustom")) {
			$('closeLinkCustom').observe('click', function(event) { magentoPopup.close();checkForVideo();
			 });
			 }
			 
			function openPopupDelay(){
				 magentoPopup.open();
			 } 
			 
			function autoClosePopup() { magentoPopup.close(); }
			<?php if ($item['delay'] != '0'):  ?>
			
			autoClosePopup.delay(<?php echo $item['delay'] ?>);
			checkForVideo.delay(<?php echo $item['delay'] ?>);
			<?php endif; ?>
			function checkForVideo() {
			if(typeof stopVideo == 'function') { stopVideo(); }	
			}
 			</script>
				<?php
				//echo 'Delay ' . $item['delay'];
				break;
			
			endforeach;
			
			
			?> 
