<?php $_config = $this->mHelper('config'); ?>
<?php $messages = $this->getMessageCollection(); ?>

var EWCookieMessage = Class.create({
    getCookie: function (c_name) {
	    if (document.cookie.length > 0) {
	        c_start = document.cookie.indexOf(c_name + "=");
	        if (c_start != -1) {
	            c_start = c_start + c_name.length + 1;
	            c_end = document.cookie.indexOf(";", c_start);
	            if (c_end == -1) c_end = document.cookie.length;
	            return unescape(document.cookie.substring(c_start, c_end));
	        }
	    }
	    return "";
	},
	
	setCookie: function setCookie(cname,cvalue,exseconds){
		if (!exseconds) exseconds = 24*60*60; // one day
		var d = new Date();
		d.setTime(d.getTime()+(exseconds*1000));
		var expires = "expires="+d.toGMTString();
		document.cookie = cname + "=" + cvalue + "; " + expires;
		return 1;
	}
});

var ewcookiemessage = new EWCookieMessage();
var ewcmCCookie = ewcookiemessage.getCookie('ewcountry');
var ewcmRCookie = ewcookiemessage.getCookie('ewregion');
function ewcmInit() {
	if (ewcookiemessage.stop) return;
	ewcookiemessage.stop = 1;
	<?php foreach ($messages as $message): ?>
		<?php if ($this->canShowMessage($message) === false) continue; ?>
		<?php 
		if ($message->hasCountries()) {
			$jsCondition = 0;
			if ($message->hasRegions()) {
				$regions = $message->getRegions();
				$countries = $message->getCountries();
				foreach ($countries as $country) {
					if (isset($regions[$country]) === false or empty($regions[$country])) {
						$jsCondition .= ' || ewcmCCookie == ' . json_encode($country);
					} else {
						$jsCondition .= ' || (ewcmCCookie == ' . json_encode($country) . ' && ' . json_encode($regions[$country]) . '.indexOf(ewcmRCookie) >= 0';
					}
					$jsCondition .= ')';
				}
			} else $jsCondition = json_encode($message->getCountries()) . '.indexOf(ewcmCCookie) >= 0';
		} else $jsCondition = 1;
		?>
		<?php if ($message->getJsCondition()): ?>
			<?php $jsCondition ='(' . $jsCondition . ') && ' . $message->getJsCondition(); ?>
		<?php endif; ?>
		if (<?php echo $jsCondition; ?>) {
			var message = <?php echo json_encode($message->getMessage()); ?>;
			message = message.replace('%%BASE_URL%%', <?php echo json_encode(rtrim(Mage::getBaseUrl(), '/')); ?>);
			$$(<?php echo json_encode($message->getElementSelector()); ?>).first().insert({ <?php echo json_encode($message->getInsertionPosition()); ?>: message });
			<?php echo $message->getJs() . "\n"; ?>
		}
	<?php endforeach; ?>
}

window.onload = function() { ewcmInit(); }
Event.observe(window, 'load', ewcmInit);
document.observe('dom:loaded', ewcmInit);

<?php foreach ($messages as $message): ?>
	<?php if ($this->canShowMessage($message) === false) continue; ?>
	<?php echo $message->getLibraryJs() . "\n"; ?>
<?php endforeach; ?>