<div id="<?php echo $this->getContainerId(); ?>" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('New ASIN Templates'); ?>">
    <?php
        echo Mage::helper('M2ePro')->__('These type of templates is used for creation of new products on Amazon.
        <ul class=list>
        <li>to create a new template, click on <i>Add New ASIN Template</i>;</li>
        <li>to assign one of the existing templates to products click on <i>Assing To This Template</i> link.</li>
        </ul>
        <b>Note:</b> The templates, which Attributes Sets are different from the Attribute Set of M2E Listing,
        cannot be assigned and they have unclickable <i>Assing To This Template</i> link.');
    ?>
</div>