<?php 
/**
 * @category    Trmmarketing
 * @package     Trmmarketing_PopupWidgets
 * @copyright   Copyright (c) 2013 TRM Marketing LLC
 * @license     http://www.trm-marketing.com/solutions/license/TRM-Marketing-Standard-License-Agreement.html
 */ 
			
			$resource = Mage::getSingleton('core/resource');
			$read= $resource->getConnection('core_read');
			$popupTable = $resource->getTableName('popup');
			$store_id = $this->helper('core')->getStoreId();
			$select = $read->select()
			   ->from($popupTable,array('popup_id', 'stores_id', 'status', 'cookie_value','sort_order'))
			   ->where('status=1')
			   ->order('sort_order ASC') ;
			   
			$popups = $read->fetchAll($select);
			?>
           <script type="text/javascript">
function addRow(content,morecontent)
{
         if (!document.getElementsByTagName) return;
         tabBody=document.getElementsByTagName("TBODY").item(0);
         row=document.createElement("TR");
         cell1 = document.createElement("TH");
         cell2 = document.createElement("TD");
         textnode1=document.createTextNode(content);
         textnode2=document.createTextNode(morecontent);
         cell1.appendChild(textnode1);
         cell2.appendChild(textnode2);
         row.appendChild(cell1);
         row.appendChild(cell2);
         tabBody.appendChild(row);
       
   
}
</script>
            <?php
			$currentStoreId = Mage::app()->getStore()->getId();
			foreach ($popups as $item) :
			$stores = explode(',', $item['stores_id']);
			if(in_array($currentStoreId, $stores) || in_array(0, $stores)) :
		
			if ($item['status'] == '1') :
			?>
       <script>
	   addRow("<?php echo strtoupper($item['cookie_value']); ?>","Promotional Pop-up cookie");
	   </script>
            <?php
			
			
			endif;
			endif;	
			endforeach;
			
			
			?> 
            
            
