<?php
/**
 * @category    Trmmarketing
 * @package     Trmmarketing_PopupWidgets
 * @copyright   Copyright (c) 2013 TRM Marketing LLC
 * @license     http://www.trm-marketing.com/solutions/license/TRM-Marketing-Standard-License-Agreement.html
 */
?>
<script>
function clearSubText(theField){
if (theField.defaultValue == theField.value)
theField.value = '';
}
function addSubText(theField) {
if (theField.value == '')
theField.value = theField .defaultValue;
} 
</script>
<div id="popup-subscribe-container">
    <!-- ajax BOF -->
    <div class="promotional-popup-loader" id="promotional-popup-loader" style="text-align:center; display:none;">
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). 'promotional-popups/promotional-popup-loader.gif'; ?>" />
	</div>	
	<div id="promotional-popup-feedback" style="display:none" class="promotional-popup-feedback">
    <?php echo $emailsuccesstext; ?>
	</div>
	<!--form name="popup-newsletter-form" id="newsletter-validate-detail-promotional-popup" method="post" onsubmit="subscribeFunction(event)"--> 
	<form name="newsletter-validate-detail-promotional-popup" id="newsletter-validate-detail-promotional-popup" method="post" onsubmit="return false;"> 
        <div class="popup-subscribe-form">
		 <div class="input-box">
          <input type="text" name="email" id="popup-newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text validate-email input-subscribe"  value="<?php echo $emaildefaulttext;  ?>" onfocus="clearSubText(this)" onblur="addSubText(this);" />
          <div id="error-promotional-popup-msg" class="validation-advice" style="display:none;">Please insert a valid email address.</div>
		</div>
				 <button type="button" title="<?php if($submitbuttonlabel != ""): echo $submitbuttonlabel; else: echo $this->__('Sign Up'); endif; ?>" onclick="subscribeFunction();" class="button"><?php if($submitbuttonlabel != ""): echo $submitbuttonlabel; else: echo $this->__('Sign Up'); endif; ?></button>
				
       </div>
    </form>	
    <script type="text/javascript">
    
        
		function subscribeFunction()
		{	
			
			var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail-promotional-popup');
			var form_email = $('popup-newsletter').getValue();
			var params_form = $('newsletter-validate-detail-promotional-popup');
			//alert(params_form);
			new Validation('popup-newsletter');
			if(validateEmailFunction(form_email))
			{
			//alert(form_email);
			//alert(Form.serialize($('newsletter-validate-detail')));
			new Ajax.Updater({ success: 'newsletter-validate-detail-promotional-popup' }, '<?php echo $this->getUrl('newsletter/subscriber/new') ?>', {
				asynchronous:true, evalScripts:false,
				parameters: { email: form_email },
				onComplete:function(request, json){Element.hide('newsletter-validate-detail-promotional-popup'); Element.hide('promotional-popup-loader'); Element.show('promotional-popup-feedback'); onSignupSuccess();},
				onLoading:function(request, json){Element.show('promotional-popup-loader'); Element.hide('newsletter-validate-detail-promotional-popup');},
				//onFailure: function(){ alert('Something went wrong...') }
				
			});

				 
				 
			}
			else
			{
			//alert(form_email);
				return false;
			}

		}	
		
		
		
function validateEmailFunction(str) {

		var at="@"
		var dot="."
		var lat=str.indexOf(at)
		var lstr=str.length
		var ldot=str.indexOf(dot)
		if (str.indexOf(at)==-1){
		   //alert("Invalid E-mail ID")
		   goProcedural()
		   return false
		}

		if (str.indexOf(at)==-1 || str.indexOf(at)==0 || str.indexOf(at)==lstr){
		   //alert("Invalid E-mail ID")
		   goProcedural()
		   return false
		}

		if (str.indexOf(dot)==-1 || str.indexOf(dot)==0 || str.indexOf(dot)==lstr){
		    //alert("Invalid E-mail ID")
		    goProcedural()
		    return false
		}

		 if (str.indexOf(at,(lat+1))!=-1){
		    //alert("Invalid E-mail ID")
		    goProcedural()
		    return false
		 }

		 if (str.substring(lat-1,lat)==dot || str.substring(lat+1,lat+2)==dot){
		    //alert("Invalid E-mail ID")
		    goProcedural()
		    return false
		 }

		 if (str.indexOf(dot,(lat+2))==-1){
		    //alert("Invalid E-mail ID")
		    goProcedural()
		    return false
		 }
		
		 if (str.indexOf(" ")!=-1){
		    //alert("Invalid E-mail ID")
		    goProcedural()
		    return false
		 }

 		 return true					
	}
function goProcedural()
{
  Element.show('error-promotional-popup-msg');
  //Element.hide.delay(5, 'error-promotional-popup-msg');
}

function onSignupSuccess() {
//alert("successful signup");

promotionalPopupConversion('<?php echo $autoclosesuccess; ?>', '<?php echo $tracksubconversion; ?>', '<?php echo $subsuccessexpiry; ?>', '<?php echo $conversionsuccessurl; ?>');

 
}
</script>
    <!-- ajax EOF -->
</div>