<?php
/**
 * @category    Trmmarketing
 * @package     Trmmarketing_PopupWidgets
 * @copyright   Copyright (c) 2013 TRM Marketing LLC
 * @license     http://www.trm-marketing.com/solutions/license/TRM-Marketing-Standard-License-Agreement.html
 */
?>


 

    <div id="popup-player"></div>

    <script>
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

     
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('popup-player', {
          height: '<?php echo $videoheight; ?>',
          width: '<?php echo $videowidth; ?>',
          videoId: '<?php echo $youtubeid; ?>',
		  playerVars: { 'rel': 0, 'showinfo': 0, <?php if ($videoautoplay == 1) {  echo "'autoplay': 1,"; } ?> },
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });
      }

     
      function onPlayerReady(event) {
		  
      }

      
      var done = false;
      function onPlayerStateChange(event) {
        
      }
      function stopVideo() {
        player.stopVideo();
      }
    </script>
