<?php if(Mage::getStoreConfig('bs_carpet/general/active')==1 && $this->getProduct()->getIsCarpetProduct()==1): ?>	
<div class="calculator-wrapper">
<div class="block block-calculator top">
    <div class="block-title calc">
        <strong><span><?php echo $this->__('Calculator')?></span></strong>
    </div>
    <div id="calculator-content" class="block-content" style="display: none;">
        <p><?php echo $this->__('Enter your room measurements to calculate the required quantity of this product:')?></p>
        
	       <div class="inneri first">
	       		<div class="inputi">
		        	<p class="inputi-f"><?php echo $this->__('Width (m)')?></p>
		        	<p class="inputi-f-s">&nbsp;</p>
		        	<p class="inputi-f"><?php echo $this->__('Length (m)')?></p>
		        </div>
		        <div class="inputi">
		        	<p class="inputi-f"><input type="text" size="5" value="" name="room_width" id="room_width" onkeyup="ca.numberOnly(this,false);"></p>
		        	<p class="inputi-f-s">X</p>
		        	<p class="inputi-f"><input type="text" size="5" value="" name="room_length" id="room_length" onkeyup="ca.numberOnly(this,false);"></p>
		        </div>
		        <?php  ?>
		        <div class="buttoni">
		        	<button type="button"  onclick="ca.calcRoom();" class="button"><span><span><?php echo $this->__('Calculate')?></span> </span> </button>
		        </div>
		        <?php  ?>
	       </div> 
	       
	        <div class="inneri">
	        	<p><b><?php echo $this->__('Floor area:')?></b> <span id="room_area">0.00</span> m<sup><font size="2">2</font></sup></p>
				<p><b><?php echo $this->__('Wall length:')?></b> <span id="room_circum">0.00</span> m</p>
				
	        </div> 
	        
	        <div class="inneri">
				
					
					<div id="large_result" style="display: block;">
						<p><b><?php echo $this->__('Current product:')?></b> <font color="#FF0066"><span id="carpet_width">0</span>m</font> x <font color="#FF0066"><span id="carpet_length">0</span>m</font></p>
						<p><b><?php echo $this->__('Actual product area:')?></b> <span id="actual_area">0.00</span> m<sup><font size="2">2</font></sup></p>
						<p><b><?php echo $this->__('Total price:')?></b> <span id="total_price"></span></p>
					</div>
					
					
					<span id="large_message" style="display: none;">
						<p><font color="#FF0000"><?php echo $this->__('Please contact one of our sales advisors about purchasing larger sizes than are available on our web site.')?></font></p>
					</span>
				
	        </div>
        
    </div>
    
</div>

<div class="block block-calculator">
    <div class="block-title conv">
        <strong><span><?php echo $this->__('Conversion')?></span></strong>
    </div>
    <div id="conversion-content" class="block-content" style="display: none;">
        <p><?php echo $this->__('Convert feet and/or inches into meters:')?></p>
        <div class="inneri">
	        <div class="inputi">
	        	<div class="inputi-f"><?php echo $this->__('Feet')?></div>
	        	<div class="inputi-f-s">&nbsp;</div>
	        	<div class="inputi-f"><?php echo $this->__('Inches')?></div>
	        </div>
	        <div class="inputi">
	        	<div class="inputi-f"><input type="text" size="5" value="" name="feet" id="calc_feet" onkeyup="ca.numberOnly(this,false);"></div>
	        	<div class="inputi-f-s">&nbsp;</div>
	        	<div class="inputi-f"><input type="text" size="5" value="" name="inches" id="calc_inches" onkeyup="ca.numberOnly(this,false);"></div>
	        </div>
	        <div class="buttoni">
	        	<button type="button"  onclick="ca.conversion();" class="button"><span><span><?php echo $this->__('Convert')?></span> </span> </button>
	        </div>
        </div>
        <div class="inneri">
	        <div class="texti">
					<p><b><?php echo $this->__('Result:')?></b> <br>
					<font color="#FF0066"><span id="calc_metres">0</span> <?php echo $this->__('meters')?></font>
					</p>
			</div>
        </div>
        
    </div>
</div>
</div>

<script type="text/javascript">
$j(document).ready(function() {
    $j('.calc').click(function(){
         $j(this).toggleClass('open');
		$j('#calculator-content').toggle();
    });
    $j('.conv').click(function(){
         $j(this).toggleClass('open');
		$j('#conversion-content').toggle();
    });
});
</script>

<?php endif;?>