<?php
$subcategories = $this->getSubcategories();
$counter = 1;
?>

<?php foreach ($subcategories as $sid): ?>
<?php $_category = Mage::getModel('catalog/category')->load($sid); ?>
<?php if ($_category): ?>
<?php 
$isActive = $_category->getIsActive();
$curl = $_category->getUrl();
$cname = $_category->getName();
?>
<li class="pronav-cat-li-sub<?php echo $sid . '-' . $counter ?>"><a class="pronav-cat-a-sub<?php echo $sid . '-' . $counter ?>" href="<?php echo $curl ?>"><?php echo $cname ?></a></li>
<?php endif; ?>
<?php $counter++;?>
<?php endforeach;?>