<?php
/**
* @author Amasty Team
* @copyright Amasty
* @package Amasty_Conf
*/
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $imageWidth = (int)Mage::getStoreConfig('amconf/size/preview_width');
    $imageHeight = (int)Mage::getStoreConfig('amconf/size/preview_height');
    $smallImageSize = Mage::getStoreConfig('amconf/size/thumb');
    $small = explode(',',$smallImageSize);
    $smallW = (int)Mage::getStoreConfig('amconf/size/thumb');
    $smallH = $smallW; //100;
    $itemCount = (int)Mage::getStoreConfig('amconf/carousel/visible_items');
?>
<?php if ('true' == (string) Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
                <div class="amlabel-div">
                <?php echo Mage::helper('amlabel')->getLabels($_product, 'product') ?>
 <?php endif; ?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<div class="product-image">
    <?php
        $_img = '<img id="amasty_zoom"
					data-zoom-image="'.$this->helper('catalog/image')->init($_product, 'image').'" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imageWidth, $imageHeight).'" 
					alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'"
				/>';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
    <div id="prevGalleryImg" class="fa fa-angle-left"></div>
    <div id="nextGalleryImg" class="fa fa-angle-right"></div>
</div>

<?php else: ?>
<div class="product-image">
    <img src="<?php echo $this->getSkinUrl('images/zoom.png')?>" alt="zoom" />
    <?php
        $_img = '<img id="amasty_zoom" data-zoom-image="'.$this->helper('catalog/image')->init($_product, 'image').'" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imageWidth, $imageHeight).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</div>
<?php endif; ?>
<?php if ('true' == (string)Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
                </div>
            <?php endif; ?>
<?php $i = 0;?>
<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <div id="amasty_gallery">
         <?php foreach ($this->getGalleryImages() as $_image): ?>
            <a class="<?php if($i == 0) { echo "active";}?>" rel="group" <?php echo Mage::getStoreConfig('amconf/lightbox/thumbnail_lignhtbox')?  ' class="fancybox" href="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()) . '"':""; ?> data-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($imageWidth, $imageHeight); ?>" data-zoom-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>"  >
                <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($smallW,$smallH); ?>" width="<?php echo $smallW;?>" height="<?php echo $smallH;?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"  title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
            </a>
            <?php $i++; ?>
         <?php endforeach; ?>
         
    </div> 

    <div id="prevGallery" class="MagicScrollArrows MagicScrollArrowPrev fa fa-angle-left"></div>
    <div id="nextGallery" class="MagicScrollArrows MagicScrollArrowNext fa fa-angle-right"></div>
     <?php if (Mage::getStoreConfig('amconf/carousel/pagination')): ?>
        <div id="ampagination"></div>
     <?php endif; ?>
</div>
<?php endif;?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
    <?php if (count($this->getGalleryImages()) > 0): ?>
        <script type="text/javascript">
            var larImg = [];
            <?php $media_gallery = $_product->getMediaGallery(); ?>
            <?php foreach ($media_gallery['images'] as $_image):?>
            larImg.push({zoomimg: '<?php echo $this->helper('catalog/image')->init($_product, 'image', $_image['file']);?>',src: '<?php echo $this->helper('catalog/image')->init($_product, 'image', $_image['file'])->resize($imageWidth, $imageHeight); ?>'});
            <?php endforeach; ?>
        </script>
    <?php endif;?>
<?php endif; ?>
<script type="text/javascript" >
    jQuery(document).ready(function(){
        AmZoomerObj = new AmZoomer(<?php echo Mage::helper('amconf/zoom')->jsParam()?>);
    })
</script>

